add solution for grid-template
js-tasks-ru/htmlcss-20230714_user6678 pull request #12
Opened 2023-08-09 10:04 UTC by Khnykin-Artem

2023-08-09 10:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-09 10:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-09 12:59 UTC, GSemikozov requested changes

2023-08-09 12:59 UTC, GSemikozov commented on components/components-preview/components-preview.css
> +  grid-template-areas: "menu . content";
если области не используются то их лучше и не задавать

2023-08-09 12:59 UTC, GSemikozov commented on components/components-preview/components-preview.css
> +  grid-template-columns: 229px 56px 1fr;
вместо колонки лучше отступ (колонка предполагает что в ней будет какой-то контент)

2023-08-09 12:59 UTC, GSemikozov commented on components/components-preview/components-preview.css
> +  grid-template-rows: 1fr;
по идее в этом нет смысла)

2023-08-09 12:59 UTC, GSemikozov commented on components/header/header.css
> +  grid-area: header;
так делать неправильно (на уровне блока задавать область) - мы заранее никогда не знает о контексте, точно так же как мы не знаем что это 100% будет встраивание в грид где разметка через области. Правильно сделать - через класс-микс (на уровне блока где создаем контекст, там же создадим элементы с установлением областей - .page__header и тд)

2023-08-09 12:59 UTC, GSemikozov commented on components/main/main.css
> +  grid-area: main;
см выше

2023-08-09 12:59 UTC, GSemikozov commented on components/wrapper/wrapper.css
> +  grid-template-areas: "header"
нет смысла

2023-08-09 12:59 UTC, GSemikozov commented on components/wrapper/wrapper.css
> +  grid-template-columns: 1fr;
лишнее

2023-08-12 20:26 UTC, GSemikozov requested changes

2023-08-12 20:26 UTC, GSemikozov commented on components/wrapper/wrapper.css
> +  grid-template-columns: 1fr;
все еще актуально

2023-08-12 20:26 UTC, GSemikozov commented on components/wrapper/wrapper.css
> +  grid-template-rows: 82px 1fr 130px;
`grid-template-rows: auto 1fr auto;` - не надо фиксировать размеры блоков по высоте

2023-08-12 20:26 UTC, GSemikozov commented on pages/template.html
> +      <footer class="footer">
wrapper__footer?

2023-08-26 20:26 UTC, merged