add solutino for checkbox
js-tasks-ru/htmlcss-20230714_user6678 pull request #17
Opened 2023-08-15 15:42 UTC by Khnykin-Artem

2023-08-15 15:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-18 10:11 UTC, GSemikozov requested changes

2023-08-18 10:11 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  position: relative;
Обязательно inline-block

2023-08-18 10:11 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled {
.checkbox__input:disabled

2023-08-18 10:11 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled .checkbox__control {
По этому состоянию см ввше

2023-08-19 19:10 UTC, GSemikozov requested changes

2023-08-19 19:10 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:disabled .checkbox__control {
так работать не будет, должно быть: `.checkbox__input:disabled ~ .checkbox__state .checkbox__control`

2023-08-19 19:10 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:disabled .checkbox__title {
и тут

2023-08-19 19:10 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:disabled .checkbox__icon {
и тут

2023-08-21 19:04 UTC, GSemikozov approved these changes

2023-08-21 19:04 UTC, merged