add solution for radio
js-tasks-ru/htmlcss-20230714_user6678 pull request #18
Opened 2023-08-16 06:56 UTC by Khnykin-Artem

2023-08-16 06:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-16 07:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-16 07:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-21 19:06 UTC, GSemikozov requested changes

2023-08-21 19:06 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio__input:disabled .radio__control {
.radio__input:disabled ~ .radio__state .radio__control (

2023-08-24 21:30 UTC, GSemikozov approved these changes

2023-08-24 21:30 UTC, merged