add solution for skeleton
js-tasks-ru/htmlcss-20230714_user6678 pull request #8
Opened 2023-07-30 18:34 UTC by Khnykin-Artem

2023-07-30 18:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-30 20:37 UTC, GSemikozov requested changes

2023-07-30 20:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  height: 20px;
высоту - на общем элементе

2023-07-30 20:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
ширину - лучше в процентах, приблизительно

2023-07-31 20:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-31 20:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-31 20:22 UTC, Khnykin-Artem commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
По поводу ширины непонятно сколько процентов от какого объекта в процентах. У разных прямоугольников разные родители

2023-08-01 15:27 UTC, GSemikozov requested changes

2023-08-01 15:27 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
так почти всегда 100% по блоку. В целом - не важно, мы привязываемся к родителю, и этого достаточно. Можно приблизительно указать - 33, 50, 75, 100

2023-08-02 06:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-02 10:02 UTC, GSemikozov requested changes

2023-08-02 10:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 515px;
и тут это лишнее

2023-08-04 09:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-05 20:42 UTC, GSemikozov approved these changes

2023-08-05 20:43 UTC, merged