add solution for calendar
js-tasks-ru/htmlcss-20230714_user6678 pull request #9
Opened 2023-08-04 15:13 UTC by Khnykin-Artem

2023-08-04 15:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-05 20:44 UTC, GSemikozov requested changes

2023-08-05 20:44 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px;
`28 26 32`

2023-08-05 20:44 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px;
border-radius не хватает

2023-08-05 20:44 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  grid-template-rows: repeat(7, 36px);
вместо 36px надо указывать 1fr, иначе теряется гибкость

2023-08-05 20:44 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 8px 9px 8px 11px;
точно без этого не обойтись?

2023-08-05 20:44 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +#first {
лучше через класс-модификатор

2023-08-07 08:34 UTC, Khnykin-Artem commented on 05-lection3/03-calendar/calendar.css
> +  padding: 8px 9px 8px 11px;
Да, я проверял

2023-08-08 05:48 UTC, GSemikozov approved these changes

2023-08-08 05:48 UTC, merged